/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DiaryEntryTypeRequest } from './diaryEntryTypeRequest';

export class CreateDiaryEntryRequest {
    'diaryEntryType': DiaryEntryTypeRequest;
    /**
    * User ID
    */
    'userId'?: string;
    /**
    * Display Date
    */
    'displayDate': Date;
    /**
    * Meta Data
    */
    'metaData': object;
    /**
    * Title
    */
    'title': string;
    /**
    * Description
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "diaryEntryType",
            "baseName": "diaryEntryType",
            "type": "DiaryEntryTypeRequest"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "displayDate",
            "baseName": "displayDate",
            "type": "Date"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "object"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateDiaryEntryRequest.attributeTypeMap;
    }
}

