/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DiaryEntryAssignmentView } from './diaryEntryAssignmentView';
import { DiaryEntryTypeRequest } from './diaryEntryTypeRequest';

export class CreateDiaryEntryAssignmentRequest {
    /**
    * The role ID.
    */
    'roleId': string;
    'diaryEntryType': DiaryEntryTypeRequest;
    'diaryEntryAssignmentView': DiaryEntryAssignmentView;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "diaryEntryType",
            "baseName": "diaryEntryType",
            "type": "DiaryEntryTypeRequest"
        },
        {
            "name": "diaryEntryAssignmentView",
            "baseName": "diaryEntryAssignmentView",
            "type": "DiaryEntryAssignmentView"
        }    ];

    static getAttributeTypeMap() {
        return CreateDiaryEntryAssignmentRequest.attributeTypeMap;
    }
}

