/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DiaryEntryReminderResponse {
    /**
    * Diary Entry Reminder Id
    */
    'diaryEntryReminderId': string;
    /**
    * User Id
    */
    'userId': string;
    /**
    * Remind At
    */
    'remindAt': Date;
    /**
    * Current count of reminders for this diary entry & user.
    */
    'count': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "diaryEntryReminderId",
            "baseName": "diaryEntryReminderId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "remindAt",
            "baseName": "remindAt",
            "type": "Date"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DiaryEntryReminderResponse.attributeTypeMap;
    }
}

