/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DiaryEntryTypeResponse } from './diaryEntryTypeResponse';

export class DiaryEntryResponse {
    /**
    * Diary Entry Id
    */
    'diaryEntryId': string;
    /**
    * Organization Id
    */
    'orgId': string;
    /**
    * Site Id
    */
    'siteId': string;
    /**
    * User ID
    */
    'userId': string | null;
    'diaryEntryType': DiaryEntryTypeResponse;
    /**
    * Display Date
    */
    'displayDate': Date;
    /**
    * Meta Data
    */
    'metaData': object;
    /**
    * Title
    */
    'title': string;
    /**
    * Description
    */
    'description': string;
    /**
    * Whether a diary entry is actioned
    */
    'isActioned': boolean;
    /**
    * Whether a diary entry is read
    */
    'isRead': boolean;
    /**
    * Reminder info
    */
    'reminderInfo': object | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "diaryEntryId",
            "baseName": "diaryEntryId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "diaryEntryType",
            "baseName": "diaryEntryType",
            "type": "DiaryEntryTypeResponse"
        },
        {
            "name": "displayDate",
            "baseName": "displayDate",
            "type": "Date"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "object"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isActioned",
            "baseName": "isActioned",
            "type": "boolean"
        },
        {
            "name": "isRead",
            "baseName": "isRead",
            "type": "boolean"
        },
        {
            "name": "reminderInfo",
            "baseName": "reminderInfo",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return DiaryEntryResponse.attributeTypeMap;
    }
}

