/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum DiaryEntryTypeCodeNames {
    ReservationExpires = <any> 'reservationExpires',
    LeaseEffectiveDate = <any> 'leaseEffectiveDate',
    LeaseExpiryDate = <any> 'leaseExpiryDate',
    ReservationStarts = <any> 'reservationStarts',
    Task = <any> 'task',
    SpaceReservationStarts = <any> 'spaceReservationStarts',
    SpaceReservationExpires = <any> 'spaceReservationExpires',
    LeaseSigned = <any> 'leaseSigned',
    LeaseMoveOutCreated = <any> 'leaseMoveOutCreated'
}
