/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateDiaryEntryRequest {
    /**
    * Mark a diary entry as actioned
    */
    'isActioned'?: boolean;
    /**
    * Mark a diary entry as read/unread
    */
    'isRead'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isActioned",
            "baseName": "isActioned",
            "type": "boolean"
        },
        {
            "name": "isRead",
            "baseName": "isRead",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateDiaryEntryRequest.attributeTypeMap;
    }
}

